### ISSUE TITLE
Waiting for CS: GO . While CS:GO is running

### ISSUE THREAD

**Issue by MattPlayGamez** [ryanocf/csgo-external-radar#12]
![image](https://user-images.githubusercontent.com/62027538/232872577-ef7ff8b7-df59-40e8-8df0-fc52758014bb.png)

**Comment by ryanocf** [comment]
Hello,

can you please tell me what the window name of your CSGO is.
You can find the window name in the task manager.

example:
![](https://i.imgur.com/8OEvdHY.png)

**Comment by MattPlayGamez** [comment]
![image](https://user-images.githubusercontent.com/62027538/233151135-2e87f014-70b6-4af2-825d-1babee2ed305.png)

**Comment by MattPlayGamez** [comment]
Same name strange

**Comment by ghost** [comment]
Have you tried hitting enter in that terminal? Sometimes stdout acts in mysterious ways

I've seen this behavior, but it had actually printed a lot of stuff afterwards and it only appeared after hitting enter 😄

**Comment by ryanocf** [comment]
if the issue still persists and you have more details about it feel free to comment.
