### ISSUE TITLE
Waiting for serverbrowser.dll...

### ISSUE THREAD

**Issue by z12crypto** [ryanocf/csgo-external-radar#13]
![image](https://user-images.githubusercontent.com/34417521/233735587-918db185-5503-42b7-81cc-726888331c43.png)

**Comment by ryanocf** [comment]
Hello,

which language does your Windows have?
also, do you use perfectworld chinese CS:GO?

**Comment by z12crypto** [comment]
对的

**Comment by z12crypto** [comment]
yes

**Comment by ryanocf** [comment]
It doesn't support perfectworld CS:GO.
sorry.

If somebody knows what is different they can open a pull request to fix.
