### ISSUE TITLE
How can i put the radar on phone?

### ISSUE THREAD

**Issue by C0st1** [ryanocf/csgo-external-radar#2]

**Comment by heli0s1** [comment]
Visit localhost:3000 on your phone browser rather than your computer after you've started the server.

**Comment by ryanocf** [comment]
> Visit localhost:3000 on your phone browser rather than your computer after you've started the server.

@heli0s1 Thanks for answering.

**Comment by ryanocf** [comment]
Oh btw. I forgot something.
Instead of localhost:3000 you need to use your LAN IPv4.

Type in cmd `ipconfig` and use the IPv4 address to view the project on your phone.
