### ISSUE TITLE
After starting the server it automatically shuts down and shows this error

### ISSUE THREAD

**Issue by Areczekk9** [ryanocf/csgo-external-radar#3]
![image](https://user-images.githubusercontent.com/75174234/138548728-8c141f99-ec31-4450-a547-f46914e05607.png)

**Comment by ryanocf** [comment]
First start the client an wait till the offsets are printed in the console.
After that start the server.

Also as described here: https://github.com/ryanocf/csgo-external-radar#usage

The application might be outdated due to several csgo updates.
You might need to update some stuff yourself.

**Comment by Areczekk9** [comment]
Thx fixed, just run as admin ;)
