### ISSUE TITLE
tl/dr, could this be changed around to work for valorant?

### ISSUE THREAD

**Issue by wasgoodymygang** [ryanocf/csgo-external-radar#4]
so if its easier message me on discord astro#3953

basically, i got the project working and its awesome, ive been trying to make a external web radar for val myself and i cant figure it out. do u have any tips or work arounds to make it for valorant? i have offsets and shit but yea lmk :)

**Comment by ryanocf** [comment]
Hey,

> could this be changed around to work for valorant?

Probably not.

The nodejs local server will be detected so you would need to host it on a vps and use a kernel driver to establish a socket connection to your server.
The only logic that maybe stays the same is the frontend code itself that you just need to feed with the data of Valorant. (Positions, Health, Name, Weapon)

Here is an example that is hardware based for a csgo web radar.
It uses C++ to host a local server and display stuff.
If you want to use your project personally only that might be a way to go to stay undetected. (Idk what vanguard detects or not tho)
https://github.com/EngineOwningSoftware/pcileech-webradar

I wish you good luck with your project.

**Comment by wasgoodymygang** [comment]
oh okay tysm :)
