### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Codi33** [ryanocf/csgo-external-radar#9]
I want to see where the players are going.
Some sort of triangle like this
![scr](https://user-images.githubusercontent.com/58087311/230690191-9655c706-b2e3-474a-8084-e99a15e707b5.png)

Also, if I have implemented it, could I make a pull request?

Thank you :)

**Comment by ryanocf** [comment]
Hello, sure.
The radar currently is not properly working in online mode.
It might be due to the method how I add and reuse entity elements in the frontend code.
I'm not sure if I will fix it soon but if you want to tackle it as well feel free to do so.
